export type ProjectStatus = 'development' | 'testing' | 'staging' | 'production' | 'archived';

export interface Project {
  id: string;
  name: string;
  aka?: string;
  status: ProjectStatus;
  color: string;
  isFavorite: boolean;
  isPinned: boolean;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  notes?: string;

  // Primary assets (multi-links)
  docsUrls?: string[];
  figmaUrls?: string[];
  
  // v2.0 environment
  url2?: string;
  dashboardUrl2?: string;
  cred2Username?: string;
  cred2Password?: string; // stored encrypted
  cred2PasswordIv?: string;

  // v3.0 environment
  url3?: string;
  dashboardUrl3?: string;
  cred3Username?: string;
  cred3Password?: string; // stored encrypted
  cred3PasswordIv?: string;
}

export type UrlCategory = 
  | 'development' 
  | 'staging' 
  | 'production' 
  | 'documentation' 
  | 'api' 
  | 'cms' 
  | 'repository' 
  | 'design' 
  | 'analytics' 
  | 'monitoring' 
  | 'other';

export interface ProjectUrl {
  id: string;
  projectId: string;
  title: string;
  url: string;
  category: UrlCategory;
  isAutoGenerated?: boolean;
  position?: number;
}

export interface Credential {
  id: string;
  projectId: string;
  title: string;
  username: string;
  email: string;
  encryptedPassword?: string;
  encryptedApiKey?: string;
  encryptedSecret?: string;
  encryptedNotes?: string;
  iv?: string; // Initialization vector for Web Crypto API AES-GCM
  isAutoGenerated?: boolean;
  position?: number;
  
  // Decrypted values (used in-memory only, never stored in DB)
  password?: string;
  apiKey?: string;
  secret?: string;
  notes?: string;
}

export interface Hosting {
  id: string;
  projectId: string;
  provider: string;
  ip: string;
  username: string;
  port: string;
  cdn: string;
  dnsProvider: string;
  notes: string;
}

export interface DatabaseInfo {
  id: string;
  projectId: string;
  type: string;
  host: string;
  port: string;
  username: string;
  encryptedPassword?: string;
  databaseName: string;
  iv?: string;

  // Decrypted values (in-memory only)
  password?: string;
}

export interface Service {
  id: string;
  projectId: string;
  name: string; // Stripe, Vercel, Supabase, etc.
  url: string;
  email: string;
  notes: string;
  position?: number;
}

export interface DomainInfo {
  id: string;
  projectId: string;
  registrar: string;
  expiryDate: string | null; // ISO string
  sslExpiry: string | null; // ISO string
  autoRenewal: boolean;
}

export type ContactRole = 'client' | 'developer' | 'designer' | 'pm' | 'support';

export interface Contact {
  id: string;
  projectId: string;
  role: ContactRole;
  name: string;
  email: string;
  phone: string;
  notes: string;
  position?: number;
}

export interface Attachment {
  id: string;
  projectId: string;
  name: string;
  type: string;
  size: number;
  data: ArrayBuffer | Blob;
  createdAt: Date;
}

export type ActivityAction = 
  | 'create' 
  | 'update' 
  | 'delete' 
  | 'restore' 
  | 'import' 
  | 'export' 
  | 'view_credential' 
  | 'copy_password';

export interface Activity {
  id: string;
  projectId: string | null;
  projectName?: string; // Cache project name for history views
  action: ActivityAction;
  details: string;
  createdAt: Date;
}

export interface VaultSettings {
  key: string;
  value: any;
}
